# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
# env:
#  - CONDA_JL_VERSION=2
os:
  - linux
  - osx
julia:
  - 1.3
  - nightly

coveralls: true
codecov: true
matrix:
  #- PYTHON=python  # python 2.7
  #- PYTHON=python3 # python 3.5
  - PYTHON=Conda-python
matrix:
  allow_failures:
    - julia: nightly
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  email: false
#
script: # the default script is equivalent to the following
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - travis_wait 30 julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build(); Pkg.test( ; coverage=true)';

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip

#script:
   #- julia --check-bounds=yes --color=yes --inline=no -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("ClimateTools"); Pkg.test("ClimateTools"; coverage=true);'

# before_install:
#   #- test "x$TRAVIS_OS_NAME" = xosx -o "x$PYTHON" = xConda-python || (sudo apt-get -qq update && sudo apt-get install -y $PYTHON)
#   - (sudo apt-get -qq update && sudo apt-get install -y python python-pip && sudo pip install cmocean)
#   - julia -e 'ENV["PYTHON"]=""; using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("PyPlot"); Pkg.add("Conda"); using Conda; Conda.add_channel("anaconda"); Conda.update(); Conda.add("numpy"); Conda.add("scipy"); Conda.add("matplotlib"); Conda.add("basemap"); Conda.add("basemap-data-hires");'
  # - julia -e 'ENV["PYTHON"]="python3"; using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("PyPlot");'

after_success:
  # - julia -e 'using Pkg; Pkg.add("Documenter");ENV["DOCUMENTER_DEBUG"]="true"; import ClimateTools; cd(joinpath(dirname(pathof(ClimateTools)), "..")); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Pkg; import ClimatePlots; cd(joinpath(dirname(pathof(ClimatePlots)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'using Pkg; import ClimatePlots; cd(joinpath(dirname(pathof(ClimatePlots)), ".."));Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
